gallery: correct category for NBDC-DDBJ Imputation Server
common-workflow-language/cwl-website pull request #179
Opened 2023-08-08 12:09 UTC by mr-c

2023-08-08 20:46 UTC, tom-tan approved these changes

2023-08-08 20:50 UTC, tom-tan requested changes
Please fix the `url` for mgnify to:
```yamll
     - title: MGnify
        url: "#mgnify" # replace "mgnify" with "#mgnify"
```

2023-08-09 09:44 UTC, mr-c commented
> Please fix the `url` for mgnify to:
> 
> ```
>      - title: MGnify
>         url: "#mgnify" # replace "mgnify" with "#mgnify"
> ```

Fixed, thank you

2023-08-09 09:55 UTC, tom-tan approved these changes

2023-08-09 09:55 UTC, merged

2023-08-09 09:56 UTC, tom-tan commented
Thanks!