Update implementations.html
common-workflow-language/cwl-website pull request #81
Opened 2021-11-10 08:37 UTC by bpmweel

With the v1 release of xenonflow I thought it would be good to have it in the list of partial implementations on the cwl website.

I discussed with @jmaassen and we agreed that the Xenon entry should point to the xenonflow repository since it's xenonflow that is developed to be a runner while Xenon has no direct support for running cwl files.

I've updated the implementation.html to reflect this

2021-11-10 11:11 UTC, mr-c approved these changes
https://deploy-preview-81--cwl-website.netlify.app/#Partial_Implementations looks good to me!

Do you want to say something about how far along you are? Like `80% of required CWL conformance tests passing` or similar?

I could even add a column for the ![required 80%](https://camo.githubusercontent.com/b4f679666fa61635c636b08c3ef234e7044aff7c5c014b5cdd31a8ff35e078f3/68747470733a2f2f62616467656e2e6e65742f68747470732f7261772e67697468756275736572636f6e74656e742e636f6d2f78656e6f6e2d6d6964646c65776172652f78656e6f6e2d666c6f772f67682d70616765732f6261646765732f72657175697265642e6a736f6e) badge

2021-11-10 14:14 UTC, bpmweel commented
> https://deploy-preview-81--cwl-website.netlify.app/#Partial_Implementations looks good to me!
> 
> Do you want to say something about how far along you are? Like `80% of required CWL conformance tests passing` or similar?
> 
> I could even add a column for the ![required 80%](https://camo.githubusercontent.com/b4f679666fa61635c636b08c3ef234e7044aff7c5c014b5cdd31a8ff35e078f3/68747470733a2f2f62616467656e2e6e65742f68747470732f7261772e67697468756275736572636f6e74656e742e636f6d2f78656e6f6e2d6d6964646c65776172652f78656e6f6e2d666c6f772f67682d70616765732f6261646765732f72657175697265642e6a736f6e) badge

That's a great suggestion. I made a commit to add a column trying to preserve the table layout.

2021-11-10 14:31 UTC, mr-c reviewed
Looks great, thanks! I've added this to the CWL meeting agenda to discuss 

https://w3id.org/cwl/meeting_minutes

about 2.5 hours from now (you are welcome to attend!)

2021-11-10 17:08 UTC, mr-c commented on content/_includes/home/implementations.html
> +|[xenonflow](https://github.com/xenon-middleware/xenonflow)|Run CWL workflows using Xenon through a REST api.|![Required](https://badgen.net/https/raw.githubusercontent.com/xenon-middleware/xenon-flo
```suggestion
|[xenonflow](https://github.com/xenon-middleware/xenonflow)|Run CWL workflows using Xenon through a REST api.|[![Required](https://badgen.net/https/raw.githubusercontent.com/xenon-middleware/xenon-flow/gh-pages/badges/required.json)](https://github.com/xenon-middleware/xenonflow#cwl-compliance)|[any Xenon backend](https://xenon-middleware.github.io/xenon/versions/3.1.0/javadoc/): local, ssh, SLURM, Torque, Grid Engine |
```
Link to the full results

2021-11-10 17:15 UTC, mr-c commented on content/_includes/home/implementations.html
> +|Software|Description|Compliance|Platform support|
```suggestion
|Software|Description|Self-Reported Compliance|Platform support|
```

2021-11-10 17:24 UTC, mr-c requested changes
Thanks! Change the column name and the link for your badges and we are happy to merge this

2021-11-11 08:54 UTC, bpmweel commented
> Thanks! Change the column name and the link for your badges and we are happy to merge this

Thank you for the suggested changes. I have committed them :)

2021-11-11 10:05 UTC, mr-c approved these changes

2021-11-11 10:07 UTC, merged

2021-11-11 11:39 UTC, mr-c commented
Thanks @bpmweel This change is live at https://www.commonwl.org/#Implementations